### ISSUE TITLE
README documentation change

### ISSUE THREAD

**Issue by UDogg** [Ansarimajid/heart#1]
# Heart Care Django Project

The Heart Care Django Project is a web application designed for heart disease hospitals to manage patient records, appointments, and medical information efficiently. This README file provides an overview of the project, installation instructions, and other relevant information.

## Features

**Appointment Scheduling**: Users can schedule appointments for patients, assign doctors, and manage the availability of doctors based on their schedule. The system also sends notifications to patients and doctors regarding upcoming appointments.

## Installation

To run the Heart Care Django Project locally, follow these steps:

1. Clone the repository: `git clone https://github.com/yourusername/heart-care-django.git`
2. Navigate to the project directory: `cd Heart-Care`
3. (Optional) Create and activate a virtual environment: `python3 -m venv myenv` and `source myenv/bin/activate`
4. Install the required dependencies: `pip install -r requirements.txt`
5. Set up the database by running migrations: `python manage.py migrate`
6. Create a superuser for accessing the admin panel: `python manage.py createsuperuser`
7. Start the development server: `python manage.py runserver`
8. Go to Heart-Care/heartcare/settings.py and add `'127.0.0.1'` to ALLOWED_HOSTS list in line 30 `ALLOWED_HOSTS = ["heart.up.railway.app", '127.0.0.1']` 
9. Open a web browser and access the application at `http://localhost:8000`

Note: Make sure you have Python and Django installed on your system before proceeding with the above steps.

## Usage

Once the application is running, you can access the different features by navigating through the user interface. The application provides a user-friendly interface for managing patient records, scheduling appointments, recording medical tests, and generating reports.

The admin panel can be accessed at `http://localhost:8000/admin`, where you can manage user accounts, permissions, and other administrative tasks.

## Contributing

Contributions to the Heart Care Django Project are welcome! If you find any issues or have suggestions for improvement, please create a new issue in the project's GitHub repository. You can also submit pull requests with bug fixes, new features, or enhancements.

Before contributing, make sure to review the project's code of conduct and guidelines for contributors, if any.

## License

The Heart Care Django Project is released under the [MIT License](https://opensource.org/licenses/MIT). You can find more details in the `LICENSE` file included with the project.

## Acknowledgements

The Heart Care Django Project is built using various open-source libraries and frameworks. We would like to acknowledge the contributions of the Django community and the developers behind the libraries used in this project. Their hard work and dedication make projects like this possible.

**Comment by Ansarimajid** [comment]
Issue was resolve : Update Documentation
